version: "3"
services:
  runners-app:
    image: runners-app:latest
    network_mode: "host"


    
#  Remove this if you postgres is not installed  locally
  # postgres:
  #   container_name: postgres
  #   image: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=runner
  #     - POSTGRES_PASSWORD=api
  #     - POSTGRES_DB=golang-practice-project
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - ./docker-volumes/postgres:/var/lib/postgresql